pipeline {
    agent {
        label 'AGENT-2'
    }
    options{
        timeout(time:10, unit:'SECONDS')
        disableConcurrentBuilds()
    }
    parameters{
        choice(name: 'ACTION', choices: ['APPLY', 'DESTROY'], description: 'Select Action')
    }
    stages {
        stage('Init') {
            steps {
                sh """
                cd 00-vpc
                terraform init -reconfigure
                """
            }
        }
        stage('Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'your-credentials-id'){
                sh 'terraform plan -out=tfplan'  
                sh 'env'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo this is deploy'
            }
        }
        stage('Print Params'){
            steps{
                echo "Choice: ${params.CHOICE}"
              
            }
        }

    }
    post{
        always{
            echo "This section runs always"
            deleteDir()
        }
    }
}
