pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time:30, unit:'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')
    }
    stages {
        stage('Init and plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'Ec2-user'){
                sh  """
                    cd 00-vpc
                    terraform init -reconfigure
                    terraform plan -out=tfplan
                  """
               }
            }
        }
        stage('Apply and Destroy') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'Ec2-user'){
                    sh """
                    cd 00-vpc
                    if [${params.ACTION}=='apply']
                    then
                      terraform apply -auto-approve tfplan
                    elif [${params.ACTION}=='destroy']
                    then
                      terraform destroy -auto-approve
                    fi
                    """
                }
            }
        }
        stage('Print Params'){
            steps{
                echo "ACTION: ${params.ACTION}"
              
            }
        }

    }
    post{
        always{
            echo "This section runs always"
            deleteDir()
        }
    }
}
